# This is a basic workflow to help you get started with Actions

name: Coverage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install simple_acme_dns package with dev dependencies
        run: |
          python3 -m pip install .
          python3 -m pip install -r requirements-dev.txt
          echo '${{ secrets.GCLOUD_DNS_JSON }}' > ./gcloud_dns.json

      - name: Test simple_acme_dns package to ensure 100% coverage
        run: |
          python3 -m coverage run --module unittest simple_acme_dns/tests/test_*
          python3 -m coverage report --show-missing --fail-under 100